codecov:
  require_ci_to_pass: true
  max_report_age: "24h"
  # strict_yaml_branch: "develop"

coverage:
  precision: 1
  round: down
  range: "70...100"

ignore:
  - "**/*Exception.java"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false